import { StyleSheet } from 'react-native'

export const colors = {
  background: '#f4f7f2',
  card: '#ffffff',
  ink: '#102c2a',
  muted: '#607471',
  border: '#dce7e2',
  accent: '#0d7770',
  accentDark: '#0c3b3b',
  accentLight: '#d9f1e8',
  warning: '#fff3d6',
  warningText: '#765313',
  error: '#a43737',
}

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 36, gap: 16 },
  header: { gap: 6 },
  eyebrow: { color: colors.accent, fontSize: 13, fontWeight: '700', letterSpacing: 1 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -0.5 },
  subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  banner: { backgroundColor: colors.warning, borderRadius: 14, padding: 14, gap: 4 },
  bannerTitle: { color: colors.warningText, fontSize: 13, fontWeight: '800' },
  bannerText: { color: colors.warningText, fontSize: 13, lineHeight: 18 },
  walletPanel: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    gap: 8,
  },
  sectionEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  walletAddress: { color: colors.ink, fontSize: 15, fontWeight: '700', marginTop: 3 },
  walletMuted: { color: colors.muted, fontSize: 13, marginTop: 3 },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accentLight,
    borderRadius: 12,
    justifyContent: 'center',
    minWidth: 82,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  secondaryButtonText: { color: colors.accentDark, fontSize: 13, fontWeight: '800' },
  buttonPressed: { opacity: 0.75 },
  buttonDisabled: { opacity: 0.55 },
  inlineError: { color: colors.error, fontSize: 13, lineHeight: 18 },
  filterLabel: { color: colors.ink, fontSize: 16, fontWeight: '800' },
  filterRow: { gap: 8, paddingVertical: 4 },
  filterChip: {
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  filterChipActive: { backgroundColor: colors.accentDark, borderColor: colors.accentDark },
  filterChipText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  filterChipTextActive: { color: '#fff' },
  opportunityCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  cardPressed: { opacity: 0.78 },
  category: { color: colors.accent, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  sampleBadge: {
    backgroundColor: colors.accentLight,
    borderRadius: 8,
    color: colors.accentDark,
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  cardTitle: { color: colors.ink, fontSize: 18, fontWeight: '800', lineHeight: 24 },
  metricGrid: { flexDirection: 'row', gap: 8 },
  metric: { backgroundColor: '#f6faf7', borderRadius: 10, flex: 1, minHeight: 56, padding: 8 },
  metricLabel: { color: colors.muted, fontSize: 10, fontWeight: '700' },
  score: { color: colors.accent, fontSize: 21, fontWeight: '900', marginTop: 2 },
  metricValue: { color: colors.ink, fontSize: 14, fontWeight: '800', marginTop: 6 },
  rewardText: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  cardLink: { color: colors.accent, fontSize: 13, fontWeight: '800' },
  stateCard: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 24,
  },
  stateTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', textAlign: 'center' },
  stateText: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' },
  retryButton: { backgroundColor: colors.accentDark, borderRadius: 12, paddingHorizontal: 18, paddingVertical: 11 },
  retryText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  flexOne: { flex: 1 },
  rowBetween: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  detailTop: { gap: 10 },
  backLink: { color: colors.accent, fontSize: 14, fontWeight: '800' },
  detailTitle: { color: colors.ink, fontSize: 27, fontWeight: '800', lineHeight: 34 },
  detailScore: {
    alignItems: 'center',
    backgroundColor: colors.accentDark,
    borderRadius: 18,
    justifyContent: 'center',
    minWidth: 92,
    padding: 14,
  },
  detailScoreLabel: { color: '#c5e9de', fontSize: 11, fontWeight: '800' },
  detailScoreValue: { color: '#fff', fontSize: 30, fontWeight: '900' },
  detailSection: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  detailSectionTitle: { color: colors.ink, fontSize: 16, fontWeight: '800' },
  detailBody: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  detailLabel: { color: colors.muted, flex: 1, fontSize: 13 },
  detailValue: { color: colors.ink, flex: 2, fontSize: 13, fontWeight: '700', textAlign: 'right' },
  openSourceButton: { alignItems: 'center', borderColor: colors.accent, borderRadius: 12, borderWidth: 1, padding: 11 },
  openSourceText: { color: colors.accent, fontSize: 13, fontWeight: '800' },
})
